version: "3.8"

services:
  postgres:
    image: library/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=P@ssw0rd
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_USER=keycloak
      - DB_PASSWORD=P@ssw0rd
      - JDBC_PARAMS=useSSL=false
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    healthcheck:
      test: "curl -f http://127.0.0.1:8080/auth || exit 1"
      start_period: 20s