insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (11, 'ACEH', '11', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (12, 'SUMATERA UTARA', '12', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (13, 'SUMATERA BARAT', '13', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (14, 'RIAU', '14', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (15, 'JAMBI', '15', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (16, 'SUMATERA SELATAN', '16', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (17, 'BENGKULU', '17', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (18, 'LAMPUNG', '18', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (19, 'KEPULAUAN BANGKA BELITUNG', '19', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (21, 'KEPULAUAN RIAU', '21', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (31, 'DKI JAKARTA', '31', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (32, 'JAWA BARAT', '32', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (33, 'JAWA TENGAH', '33', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (34, 'DI YOGYAKARTA', '34', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (35, 'JAWA TIMUR', '35', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (36, 'BANTEN', '36', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (51, 'BALI', '51', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (52, 'NUSA TENGGARA BARAT', '52', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (53, 'NUSA TENGGARA TIMUR', '53', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (61, 'KALIMANTAN BARAT', '61', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (62, 'KALIMANTAN TENGAH', '62', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (63, 'KALIMANTAN SELATAN', '63', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (64, 'KALIMANTAN TIMUR', '64', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (65, 'KALIMANTAN UTARA', '65', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (71, 'SULAWESI UTARA', '71', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (72, 'SULAWESI TENGAH', '72', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (73, 'SULAWESI SELATAN', '73', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (74, 'SULAWESI TENGGARA', '74', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (75, 'GORONTALO', '75', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (76, 'SULAWESI BARAT', '76', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (81, 'MALUKU', '81', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (82, 'MALUKU UTARA', '82', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (94, 'PAPUA', '91', now());
insert into master_provinsi(kode_provinsi, nama_provinsi, kode_provinsi_capil, created_at) VALUES (91, 'PAPUA BARAT', '92', now());