insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1101', '1109', 'KABUPATEN SIMEULUE', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1102', '1110', 'KABUPATEN ACEH SINGKIL', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1103', '1101', 'KABUPATEN ACEH SELATAN', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1104', '1102', 'KABUPATEN ACEH TENGGARA', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1105', '1103', 'KABUPATEN ACEH TIMUR', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1106', '1104', 'KABUPATEN ACEH TENGAH', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1107', '1105', 'KABUPATEN ACEH BARAT', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1108', '1106', 'KABUPATEN ACEH BESAR', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1109', '1107', 'KABUPATEN PIDIE', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1110', '1111', 'KABUPATEN BIREUEN', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1111', '1108', 'KABUPATEN ACEH UTARA', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1112', '1112', 'KABUPATEN ACEH BARAT DAYA', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1113', '1113', 'KABUPATEN GAYO LUES', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1114', '1116', 'KABUPATEN ACEH TAMIANG', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1115', '1115', 'KABUPATEN NAGAN RAYA', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1116', '1114', 'KABUPATEN ACEH JAYA', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1117', '1117', 'KABUPATEN BENER MERIAH', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1118', '1118', 'KABUPATEN PIDIE JAYA', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1171', '1171', 'KOTA BANDA ACEH', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1172', '1172', 'KOTA SABANG', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1173', '1174', 'KOTA LANGSA', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1174', '1173', 'KOTA LHOKSEUMAWE', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1175', '1175', 'KOTA SUBULUSSALAM', '11', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1201', '1204', 'KABUPATEN NIAS', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1202', '1213', 'KABUPATEN MANDAILING NATAL', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1203', '1203', 'KABUPATEN TAPANULI SELATAN', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1204', '1201', 'KABUPATEN TAPANULI TENGAH', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1205', '1202', 'KABUPATEN TAPANULI UTARA', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1206', '1212', 'KABUPATEN TOBA SAMOSIR', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1207', '1210', 'KABUPATEN LABUHAN BATU', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1208', '1209', 'KABUPATEN ASAHAN', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1209', '1208', 'KABUPATEN SIMALUNGUN', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1210', '1211', 'KABUPATEN DAIRI', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1211', '1206', 'KABUPATEN KARO', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1212', '1207', 'KABUPATEN DELI SERDANG', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1213', '1205', 'KABUPATEN LANGKAT', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1214', '1214', 'KABUPATEN NIAS SELATAN', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1215', '1216', 'KABUPATEN HUMBANG HASUNDUTAN', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1216', '1215', 'KABUPATEN PAKPAK BHARAT', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1217', '1217', 'KABUPATEN SAMOSIR', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1218', '1218', 'KABUPATEN SERDANG BEDAGAI', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1219', '1219', 'KABUPATEN BATU BARA', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1220', '1220', 'KABUPATEN PADANG LAWAS UTARA', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1221', '1221', 'KABUPATEN PADANG LAWAS', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1222', '1222', 'KABUPATEN LABUHAN BATU SELATAN', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1223', '1223', 'KABUPATEN LABUHAN BATU UTARA', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1224', '1224', 'KABUPATEN NIAS UTARA', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1225', '1225', 'KABUPATEN NIAS BARAT', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1271', '1273', 'KOTA SIBOLGA', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1272', '1274', 'KOTA TANJUNG BALAI', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1273', '1272', 'KOTA PEMATANG SIANTAR', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1274', '1276', 'KOTA TEBING TINGGI', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1275', '1271', 'KOTA MEDAN', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1276', '1275', 'KOTA BINJAI', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1277', '1277', 'KOTA PADANGSIDIMPUAN', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1278', '1278', 'KOTA GUNUNGSITOLI', '12', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1301', '1309', 'KABUPATEN KEPULAUAN MENTAWAI', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1302', '1301', 'KABUPATEN PESISIR SELATAN', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1303', '1302', 'KABUPATEN SOLOK', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1304', '1303', 'KABUPATEN SIJUNJUNG', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1305', '1304', 'KABUPATEN TANAH DATAR', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1306', '1305', 'KABUPATEN PADANG PARIAMAN', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1307', '1306', 'KABUPATEN AGAM', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1308', '1307', 'KABUPATEN LIMA PULUH KOTA', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1309', '1308', 'KABUPATEN PASAMAN', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1310', '1311', 'KABUPATEN SOLOK SELATAN', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1311', '1310', 'KABUPATEN DHARMASRAYA', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1312', '1312', 'KABUPATEN PASAMAN BARAT', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1371', '1371', 'KOTA PADANG', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1372', '1372', 'KOTA SOLOK', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1373', '1373', 'KOTA SAWAH LUNTO', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1374', '1374', 'KOTA PADANG PANJANG', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1375', '1375', 'KOTA BUKITTINGGI', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1376', '1376', 'KOTA PAYAKUMBUH', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1377', '1377', 'KOTA PARIAMAN', '13', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1401', '1409', 'KABUPATEN KUANTAN SINGINGI', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1402', '1402', 'KABUPATEN INDRAGIRI HULU', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1403', '1404', 'KABUPATEN INDRAGIRI HILIR', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1404', '1405', 'KABUPATEN PELALAWAN', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1405', '1408', 'KABUPATEN SIAK', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1406', '1401', 'KABUPATEN KAMPAR', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1407', '1406', 'KABUPATEN ROKAN HULU', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1408', '1403', 'KABUPATEN BENGKALIS', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1409', '1407', 'KABUPATEN ROKAN HILIR', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1410', '1410', 'KABUPATEN KEPULAUAN MERANTI', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1471', '1471', 'KOTA PEKANBARU', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1473', '1472', 'KOTA DUMAI', '14', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1501', '1501', 'KABUPATEN KERINCI', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1502', '1502', 'KABUPATEN MERANGIN', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1503', '1503', 'KABUPATEN SAROLANGUN', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1504', '1504', 'KABUPATEN BATANG HARI', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1505', '1505', 'KABUPATEN MUARO JAMBI', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1506', '1507', 'KABUPATEN TANJUNG JABUNG TIMUR', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1507', '1506', 'KABUPATEN TANJUNG JABUNG BARAT', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1508', '1509', 'KABUPATEN TEBO', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1509', '1508', 'KABUPATEN BUNGO', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1571', '1571', 'KOTA JAMBI', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1572', '1572', 'KOTA SUNGAI PENUH', '15', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1601', '1601', 'KABUPATEN OGAN KOMERING ULU', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1602', '1602', 'KABUPATEN OGAN KOMERING ILIR', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1603', '1603', 'KABUPATEN MUARA ENIM', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1604', '1604', 'KABUPATEN LAHAT', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1605', '1605', 'KABUPATEN MUSI RAWAS', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1606', '1606', 'KABUPATEN MUSI BANYUASIN', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1607', '1607', 'KABUPATEN BANYU ASIN', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1608', '1609', 'KABUPATEN OGAN KOMERING ULU SELATAN', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1609', '1608', 'KABUPATEN OGAN KOMERING ULU TIMUR', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1610', '1610', 'KABUPATEN OGAN ILIR', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1611', '1611', 'KABUPATEN EMPAT LAWANG', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1612', '1612', 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1613', '1613', 'KABUPATEN MUSI RAWAS UTARA', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1671', '1671', 'KOTA PALEMBANG', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1672', '1674', 'KOTA PRABUMULIH', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1673', '1672', 'KOTA PAGAR ALAM', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1674', '1673', 'KOTA LUBUKLINGGAU', '16', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1701', '1701', 'KABUPATEN BENGKULU SELATAN', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1702', '1702', 'KABUPATEN REJANG LEBONG', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1703', '1703', 'KABUPATEN BENGKULU UTARA', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1704', '1704', 'KABUPATEN KAUR', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1705', '1705', 'KABUPATEN SELUMA', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1706', '1706', 'KABUPATEN MUKOMUKO', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1707', '1707', 'KABUPATEN LEBONG', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1708', '1708', 'KABUPATEN KEPAHIANG', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1709', '1709', 'KABUPATEN BENGKULU TENGAH', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1771', '1771', 'KOTA BENGKULU', '17', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1801', '1804', 'KABUPATEN LAMPUNG BARAT', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1802', '1806', 'KABUPATEN TANGGAMUS', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1803', '1801', 'KABUPATEN LAMPUNG SELATAN', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1804', '1807', 'KABUPATEN LAMPUNG TIMUR', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1805', '1802', 'KABUPATEN LAMPUNG TENGAH', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1806', '1803', 'KABUPATEN LAMPUNG UTARA', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1807', '1808', 'KABUPATEN WAY KANAN', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1808', '1805', 'KABUPATEN TULANGBAWANG', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1809', '1809', 'KABUPATEN PESAWARAN', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1810', '1810', 'KABUPATEN PRINGSEWU', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1811', '1811', 'KABUPATEN MESUJI', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1812', '1812', 'KABUPATEN TULANG BAWANG BARAT', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1813', '1813', 'KABUPATEN PESISIR BARAT', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1871', '1871', 'KOTA BANDAR LAMPUNG', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1872', '1872', 'KOTA METRO', '18', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1901', '1901', 'KABUPATEN BANGKA', '19', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1902', '1902', 'KABUPATEN BELITUNG', '19', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1903', '1905', 'KABUPATEN BANGKA BARAT', '19', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1904', '1904', 'KABUPATEN BANGKA TENGAH', '19', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1905', '1903', 'KABUPATEN BANGKA SELATAN', '19', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1906', '1906', 'KABUPATEN BELITUNG TIMUR', '19', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('1971', '1971', 'KOTA PANGKAL PINANG', '19', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('2101', '2102', 'KABUPATEN KARIMUN', '21', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('2102', '2101', 'KABUPATEN BINTAN', '21', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('2103', '2103', 'KABUPATEN NATUNA', '21', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('2104', '2104', 'KABUPATEN LINGGA', '21', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('2105', '2105', 'KABUPATEN KEPULAUAN ANAMBAS', '21', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('2171', '2171', 'KOTA BATAM', '21', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('2172', '2172', 'KOTA TANJUNG PINANG', '21', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3101', '3101', 'ADM. KEPULAUAN SERIBU', '31', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3171', '3174', 'KOTA JAKARTA SELATAN', '31', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3172', '3175', 'KOTA JAKARTA TIMUR', '31', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3173', '3171', 'KOTA JAKARTA PUSAT', '31', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3174', '3173', 'KOTA JAKARTA BARAT', '31', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3175', '3172', 'KOTA JAKARTA UTARA', '31', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3201', '3201', 'KABUPATEN BOGOR', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3202', '3202', 'KABUPATEN SUKABUMI', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3203', '3203', 'KABUPATEN CIANJUR', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3204', '3204', 'KABUPATEN BANDUNG', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3205', '3205', 'KABUPATEN GARUT', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3206', '3206', 'KABUPATEN TASIKMALAYA', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3207', '3207', 'KABUPATEN CIAMIS', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3208', '3208', 'KABUPATEN KUNINGAN', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3209', '3209', 'KABUPATEN CIREBON', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3210', '3210', 'KABUPATEN MAJALENGKA', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3211', '3211', 'KABUPATEN SUMEDANG', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3212', '3212', 'KABUPATEN INDRAMAYU', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3213', '3213', 'KABUPATEN SUBANG', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3214', '3214', 'KABUPATEN PURWAKARTA', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3215', '3215', 'KABUPATEN KARAWANG', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3216', '3216', 'KABUPATEN BEKASI', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3217', '3217', 'KABUPATEN BANDUNG BARAT', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3218', '3218', 'KABUPATEN PANGANDARAN', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3271', '3271', 'KOTA BOGOR', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3272', '3272', 'KOTA SUKABUMI', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3273', '3273', 'KOTA BANDUNG', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3274', '3274', 'KOTA CIREBON', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3275', '3275', 'KOTA BEKASI', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3276', '3276', 'KOTA DEPOK', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3277', '3277', 'KOTA CIMAHI', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3278', '3278', 'KOTA TASIKMALAYA', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3279', '3279', 'KOTA BANJAR', '32', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3301', '3301', 'KABUPATEN CILACAP', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3302', '3302', 'KABUPATEN BANYUMAS', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3303', '3303', 'KABUPATEN PURBALINGGA', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3304', '3304', 'KABUPATEN BANJARNEGARA', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3305', '3305', 'KABUPATEN KEBUMEN', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3306', '3306', 'KABUPATEN PURWOREJO', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3307', '3307', 'KABUPATEN WONOSOBO', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3308', '3308', 'KABUPATEN MAGELANG', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3309', '3309', 'KABUPATEN BOYOLALI', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3310', '3310', 'KABUPATEN KLATEN', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3311', '3311', 'KABUPATEN SUKOHARJO', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3312', '3312', 'KABUPATEN WONOGIRI', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3313', '3313', 'KABUPATEN KARANGANYAR', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3314', '3314', 'KABUPATEN SRAGEN', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3315', '3315', 'KABUPATEN GROBOGAN', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3316', '3316', 'KABUPATEN BLORA', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3317', '3317', 'KABUPATEN REMBANG', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3318', '3318', 'KABUPATEN PATI', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3319', '3319', 'KABUPATEN KUDUS', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3320', '3320', 'KABUPATEN JEPARA', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3321', '3321', 'KABUPATEN DEMAK', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3322', '3322', 'KABUPATEN SEMARANG', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3323', '3323', 'KABUPATEN TEMANGGUNG', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3324', '3324', 'KABUPATEN KENDAL', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3325', '3325', 'KABUPATEN BATANG', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3326', '3326', 'KABUPATEN PEKALONGAN', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3327', '3327', 'KABUPATEN PEMALANG', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3328', '3328', 'KABUPATEN TEGAL', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3329', '3329', 'KABUPATEN BREBES', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3371', '3371', 'KOTA MAGELANG', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3372', '3372', 'KOTA SURAKARTA', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3373', '3373', 'KOTA SALATIGA', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3374', '3374', 'KOTA SEMARANG', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3375', '3375', 'KOTA PEKALONGAN', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3376', '3376', 'KOTA TEGAL', '33', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3401', '3401', 'KABUPATEN KULON PROGO', '34', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3402', '3402', 'KABUPATEN BANTUL', '34', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3403', '3403', 'KABUPATEN GUNUNG KIDUL', '34', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3404', '3404', 'KABUPATEN SLEMAN', '34', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3471', '3471', 'KOTA YOGYAKARTA', '34', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3501', '3501', 'KABUPATEN PACITAN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3502', '3502', 'KABUPATEN PONOROGO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3503', '3503', 'KABUPATEN TRENGGALEK', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3504', '3504', 'KABUPATEN TULUNGAGUNG', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3505', '3505', 'KABUPATEN BLITAR', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3506', '3506', 'KABUPATEN KEDIRI', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3507', '3507', 'KABUPATEN MALANG', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3508', '3508', 'KABUPATEN LUMAJANG', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3509', '3509', 'KABUPATEN JEMBER', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3510', '3510', 'KABUPATEN BANYUWANGI', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3511', '3511', 'KABUPATEN BONDOWOSO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3512', '3512', 'KABUPATEN SITUBONDO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3513', '3513', 'KABUPATEN PROBOLINGGO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3514', '3514', 'KABUPATEN PASURUAN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3515', '3515', 'KABUPATEN SIDOARJO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3516', '3516', 'KABUPATEN MOJOKERTO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3517', '3517', 'KABUPATEN JOMBANG', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3518', '3518', 'KABUPATEN NGANJUK', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3519', '3519', 'KABUPATEN MADIUN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3520', '3520', 'KABUPATEN MAGETAN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3521', '3521', 'KABUPATEN NGAWI', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3522', '3522', 'KABUPATEN BOJONEGORO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3523', '3523', 'KABUPATEN TUBAN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3524', '3524', 'KABUPATEN LAMONGAN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3525', '3525', 'KABUPATEN GRESIK', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3526', '3526', 'KABUPATEN BANGKALAN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3527', '3527', 'KABUPATEN SAMPANG', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3528', '3528', 'KABUPATEN PAMEKASAN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3529', '3529', 'KABUPATEN SUMENEP', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3571', '3571', 'KOTA KEDIRI', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3572', '3572', 'KOTA BLITAR', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3573', '3573', 'KOTA MALANG', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3574', '3574', 'KOTA PROBOLINGGO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3575', '3575', 'KOTA PASURUAN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3576', '3576', 'KOTA MOJOKERTO', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3577', '3577', 'KOTA MADIUN', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3578', '3578', 'KOTA SURABAYA', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3579', '3579', 'KOTA BATU', '35', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3601', '3601', 'KABUPATEN PANDEGLANG', '36', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3602', '3602', 'KABUPATEN LEBAK', '36', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3603', '3603', 'KABUPATEN TANGERANG', '36', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3604', '3604', 'KABUPATEN SERANG', '36', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3671', '3671', 'KOTA TANGERANG', '36', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3672', '3672', 'KOTA CILEGON', '36', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3673', '3673', 'KOTA SERANG', '36', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('3674', '3674', 'KOTA TANGERANG SELATAN', '36', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5101', '5101', 'KABUPATEN JEMBRANA', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5102', '5102', 'KABUPATEN TABANAN', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5103', '5103', 'KABUPATEN BADUNG', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5104', '5104', 'KABUPATEN GIANYAR', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5105', '5105', 'KABUPATEN KLUNGKUNG', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5106', '5106', 'KABUPATEN BANGLI', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5107', '5107', 'KABUPATEN KARANG ASEM', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5108', '5108', 'KABUPATEN BULELENG', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5171', '5171', 'KOTA DENPASAR', '51', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5201', '5201', 'KABUPATEN LOMBOK BARAT', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5202', '5202', 'KABUPATEN LOMBOK TENGAH', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5203', '5203', 'KABUPATEN LOMBOK TIMUR', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5204', '5204', 'KABUPATEN SUMBAWA', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5205', '5205', 'KABUPATEN DOMPU', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5206', '5206', 'KABUPATEN BIMA', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5207', '5207', 'KABUPATEN SUMBAWA BARAT', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5208', '5208', 'KABUPATEN LOMBOK UTARA', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5271', '5271', 'KOTA MATARAM', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5272', '5272', 'KOTA BIMA', '52', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5301', '5312', 'KABUPATEN SUMBA BARAT', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5302', '5311', 'KABUPATEN SUMBA TIMUR', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5303', '5301', 'KABUPATEN KUPANG', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5304', '5302', 'KABUPATEN TIMOR TENGAH SELATAN', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5305', '5303', 'KABUPATEN TIMOR TENGAH UTARA', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5306', '5304', 'KABUPATEN BELU', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5307', '5305', 'KABUPATEN ALOR', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5308', '5313', 'KABUPATEN LEMBATA', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5309', '5306', 'KABUPATEN FLORES TIMUR', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5310', '5307', 'KABUPATEN SIKKA', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5311', '5308', 'KABUPATEN ENDE', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5312', '5309', 'KABUPATEN NGADA', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5313', '5310', 'KABUPATEN MANGGARAI', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5314', '5314', 'KABUPATEN ROTE NDAO', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5315', '5315', 'KABUPATEN MANGGARAI BARAT', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5316', '5317', 'KABUPATEN SUMBA TENGAH', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5317', '5318', 'KABUPATEN SUMBA BARAT DAYA', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5318', '5316', 'KABUPATEN NAGEKEO', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5319', '5319', 'KABUPATEN MANGGARAI TIMUR', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5320', '5320', 'KABUPATEN SABU RAIJUA', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5321', '5321', 'KABUPATEN MALAKA', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('5371', '5371', 'KOTA KUPANG', '53', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6101', '6101', 'KABUPATEN SAMBAS', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6102', '6107', 'KABUPATEN BENGKAYANG', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6103', '6108', 'KABUPATEN LANDAK', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6104', '6102', 'KABUPATEN MEMPAWAH', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6105', '6103', 'KABUPATEN SANGGAU', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6106', '6104', 'KABUPATEN KETAPANG', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6107', '6105', 'KABUPATEN SINTANG', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6108', '6106', 'KABUPATEN KAPUAS HULU', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6109', '6109', 'KABUPATEN SEKADAU', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6110', '6110', 'KABUPATEN MELAWI', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6111', '6111', 'KABUPATEN KAYONG UTARA', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6112', '6112', 'KABUPATEN KUBU RAYA', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6171', '6171', 'KOTA PONTIANAK', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6172', '6172', 'KOTA SINGKAWANG', '61', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6201', '6201', 'KABUPATEN KOTAWARINGIN BARAT', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6202', '6202', 'KABUPATEN KOTAWARINGIN TIMUR', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6203', '6203', 'KABUPATEN KAPUAS', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6204', '6204', 'KABUPATEN BARITO SELATAN', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6205', '6205', 'KABUPATEN BARITO UTARA', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6206', '6208', 'KABUPATEN SUKAMARA', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6207', '6209', 'KABUPATEN LAMANDAU', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6208', '6207', 'KABUPATEN SERUYAN', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6209', '6206', 'KABUPATEN KATINGAN', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6210', '6211', 'KABUPATEN PULANG PISAU', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6211', '6210', 'KABUPATEN GUNUNG MAS', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6212', '6213', 'KABUPATEN BARITO TIMUR', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6213', '6212', 'KABUPATEN MURUNG RAYA', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6271', '6271', 'KOTA PALANGKA RAYA', '62', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6301', '6301', 'KABUPATEN TANAH LAUT', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6302', '6302', 'KABUPATEN KOTA BARU', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6303', '6303', 'KABUPATEN BANJAR', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6304', '6304', 'KABUPATEN BARITO KUALA', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6305', '6305', 'KABUPATEN TAPIN', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6306', '6306', 'KABUPATEN HULU SUNGAI SELATAN', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6307', '6307', 'KABUPATEN HULU SUNGAI TENGAH', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6308', '6308', 'KABUPATEN HULU SUNGAI UTARA', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6309', '6309', 'KABUPATEN TABALONG', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6310', '6310', 'KABUPATEN TANAH BUMBU', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6311', '6311', 'KABUPATEN BALANGAN', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6371', '6371', 'KOTA BANJARMASIN', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6372', '6372', 'KOTA BANJAR BARU', '63', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6401', '6401', 'KABUPATEN PASER', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6402', '6407', 'KABUPATEN KUTAI BARAT', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6403', '6402', 'KABUPATEN KUTAI KARTANEGARA', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6404', '6408', 'KABUPATEN KUTAI TIMUR', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6405', '6403', 'KABUPATEN BERAU', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6409', '6409', 'KABUPATEN PENAJAM PASER UTARA', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6411', '6411', 'KABUPATEN MAHAKAM HULU', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6471', '6471', 'KOTA BALIKPAPAN', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6472', '6472', 'KOTA SAMARINDA', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6474', '6474', 'KOTA BONTANG', '64', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6501', '6502', 'KABUPATEN MALINAU', '65', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6502', '6501', 'KABUPATEN BULUNGAN', '65', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6503', '6504', 'KABUPATEN TANA TIDUNG', '65', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6504', '6503', 'KABUPATEN NUNUKAN', '65', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('6571', '6571', 'KOTA TARAKAN', '65', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7101', '7101', 'KABUPATEN BOLAANG MONGONDOW', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7102', '7102', 'KABUPATEN MINAHASA', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7103', '7103', 'KABUPATEN KEPULAUAN SANGIHE', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7104', '7104', 'KABUPATEN KEPULAUAN TALAUD', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7105', '7105', 'KABUPATEN MINAHASA SELATAN', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7106', '7106', 'KABUPATEN MINAHASA UTARA', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7107', '7108', 'KABUPATEN BOLAANG MONGONDOW UTARA', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7108', '7109', 'KABUPATEN SIAU TAGULANDANG BIARO', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7109', '7107', 'KABUPATEN MINAHASA TENGGARA', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7110', '7111', 'KABUPATEN BOLAANG MONGONDOW SELATAN', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7111', '7110', 'KABUPATEN BOLAANG MONGONDOW TIMUR', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7171', '7171', 'KOTA MANADO', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7172', '7172', 'KOTA BITUNG', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7173', '7173', 'KOTA TOMOHON', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7174', '7174', 'KOTA KOTAMOBAGU', '71', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7201', '7207', 'KABUPATEN BANGGAI KEPULAUAN', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7202', '7201', 'KABUPATEN BANGGAI', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7203', '7206', 'KABUPATEN MOROWALI', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7204', '7202', 'KABUPATEN POSO', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7205', '7203', 'KABUPATEN DONGGALA', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7206', '7204', 'KABUPATEN TOLI-TOLI', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7207', '7205', 'KABUPATEN BUOL', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7208', '7208', 'KABUPATEN PARIGI MOUTONG', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7209', '7209', 'KABUPATEN TOJO UNA-UNA', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7210', '7210', 'KABUPATEN SIGI', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7211', '7211', 'KABUPATEN BANGGAI LAUT', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7212', '7212', 'KABUPATEN MOROWALI UTARA', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7271', '7271', 'KOTA PALU', '72', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7301', '7301', 'KABUPATEN KEPULAUAN SELAYAR', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7302', '7302', 'KABUPATEN BULUKUMBA', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7303', '7303', 'KABUPATEN BANTAENG', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7304', '7304', 'KABUPATEN JENEPONTO', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7305', '7305', 'KABUPATEN TAKALAR', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7306', '7306', 'KABUPATEN GOWA', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7307', '7307', 'KABUPATEN SINJAI', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7308', '7309', 'KABUPATEN MAROS', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7309', '7310', 'KABUPATEN PANGKAJENE DAN KEPULAUAN', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7310', '7311', 'KABUPATEN BARRU', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7311', '7308', 'KABUPATEN BONE', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7312', '7312', 'KABUPATEN SOPPENG', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7313', '7313', 'KABUPATEN WAJO', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7314', '7314', 'KABUPATEN SIDENRENG RAPPANG', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7315', '7315', 'KABUPATEN PINRANG', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7316', '7316', 'KABUPATEN ENREKANG', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7317', '7317', 'KABUPATEN LUWU', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7318', '7318', 'KABUPATEN TANA TORAJA', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7322', '7322', 'KABUPATEN LUWU UTARA', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7325', '7324', 'KABUPATEN LUWU TIMUR', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7326', '7326', 'KABUPATEN TORAJA UTARA', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7371', '7371', 'KOTA MAKASSAR', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7372', '7372', 'KOTA PAREPARE', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7373', '7373', 'KOTA PALOPO', '73', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7401', '7404', 'KABUPATEN BUTON', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7402', '7403', 'KABUPATEN MUNA', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7403', '7402', 'KABUPATEN KONAWE', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7404', '7401', 'KABUPATEN KOLAKA', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7405', '7405', 'KABUPATEN KONAWE SELATAN', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7406', '7406', 'KABUPATEN BOMBANA', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7407', '7407', 'KABUPATEN WAKATOBI', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7408', '7408', 'KABUPATEN KOLAKA UTARA', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7409', '7410', 'KABUPATEN BUTON UTARA', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7410', '7409', 'KABUPATEN KONAWE UTARA', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7411', '7411', 'KABUPATEN KOLAKA TIMUR', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7412', '7412', 'KABUPATEN KONAWE KEPULAUAN', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7413', '7413', 'KABUPATEN MUNA BARAT', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7414', '7414', 'KABUPATEN BUTON TENGAH', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7415', '7415', 'KABUPATEN BUTON SELATAN', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7471', '7471', 'KOTA KENDARI', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7472', '7472', 'KOTA BAUBAU', '74', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7501', '7502', 'KABUPATEN BOALEMO', '75', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7502', '7501', 'KABUPATEN GORONTALO', '75', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7503', '7504', 'KABUPATEN POHUWATO', '75', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7504', '7503', 'KABUPATEN BONE BOLANGO', '75', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7505', '7505', 'KABUPATEN GORONTALO UTARA', '75', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7571', '7571', 'KOTA GORONTALO', '75', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7601', '7605', 'KABUPATEN MAJENE', '76', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7602', '7604', 'KABUPATEN POLEWALI MANDAR', '76', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7603', '7603', 'KABUPATEN MAMASA', '76', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7604', '7602', 'KABUPATEN MAMUJU', '76', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7605', '7601', 'KABUPATEN MAMUJU UTARA', '76', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('7606', '7606', 'KABUPATEN MAMUJU TENGAH', '76', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8101', '8103', 'KABUPATEN MALUKU TENGGARA BARAT', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8102', '8102', 'KABUPATEN MALUKU TENGGARA', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8103', '8101', 'KABUPATEN MALUKU TENGAH', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8104', '8104', 'KABUPATEN BURU', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8105', '8107', 'KABUPATEN KEPULAUAN ARU', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8106', '8106', 'KABUPATEN SERAM BAGIAN BARAT', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8107', '8105', 'KABUPATEN SERAM BAGIAN TIMUR', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8108', '8108', 'KABUPATEN MALUKU BARAT DAYA', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8109', '8109', 'KABUPATEN BURU SELATAN', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8171', '8171', 'KOTA AMBON', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8172', '8172', 'KOTA TUAL', '81', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8201', '8201', 'KABUPATEN HALMAHERA BARAT', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8202', '8202', 'KABUPATEN HALMAHERA TENGAH', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8203', '8205', 'KABUPATEN KEPULAUAN SULA', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8204', '8204', 'KABUPATEN HALMAHERA SELATAN', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8205', '8203', 'KABUPATEN HALMAHERA UTARA', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8206', '8206', 'KABUPATEN HALMAHERA TIMUR', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8207', '8207', 'KABUPATEN PULAU MOROTAI', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8208', '8208', 'KABUPATEN PULAU TALIABU', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8271', '8271', 'KOTA TERNATE', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('8272', '8272', 'KOTA TIDORE KEPULAUAN', '82', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9101', '9203', 'KABUPATEN FAKFAK', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9102', '9208', 'KABUPATEN KAIMANA', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9103', '9207', 'KABUPATEN TELUK WONDAMA', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9104', '9206', 'KABUPATEN TELUK BINTUNI', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9105', '9202', 'KABUPATEN MANOKWARI', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9106', '9204', 'KABUPATEN SORONG SELATAN', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9107', '9201', 'KABUPATEN SORONG', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9108', '9205', 'KABUPATEN RAJA AMPAT', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9109', '9209', 'KABUPATEN TAMBRAUW', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9110', '9210', 'KABUPATEN MAYBRAT', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9111', '9211', 'KABUPATEN MANOKWARI SELATAN', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9112', '9212', 'KABUPATEN PEGUNUNGAN ARFAK', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9171', '9271', 'KOTA SORONG', '91', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9401', '9101', 'KABUPATEN MERAUKE', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9402', '9102', 'KABUPATEN JAYAWIJAYA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9403', '9103', 'KABUPATEN JAYAPURA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9404', '9104', 'KABUPATEN NABIRE', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9408', '9105', 'KABUPATEN KEPULAUAN YAPEN', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9409', '9106', 'KABUPATEN BIAK NUMFOR', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9410', '9108', 'KABUPATEN PANIAI', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9411', '9107', 'KABUPATEN PUNCAK JAYA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9412', '9109', 'KABUPATEN MIMIKA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9413', '9116', 'KABUPATEN BOVEN DIGOEL', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9414', '9117', 'KABUPATEN MAPPI', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9415', '9118', 'KABUPATEN ASMAT', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9416', '9113', 'KABUPATEN YAHUKIMO', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9417', '9112', 'KABUPATEN PEGUNUNGAN BINTANG', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9418', '9114', 'KABUPATEN TOLIKARA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9419', '9110', 'KABUPATEN SARMI', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9420', '9111', 'KABUPATEN KEEROM', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9426', '9115', 'KABUPATEN WAROPEN', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9427', '9119', 'KABUPATEN SUPIORI', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9428', '9120', 'KABUPATEN MAMBERAMO RAYA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9429', '9124', 'KABUPATEN NDUGA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9430', '9123', 'KABUPATEN LANNY JAYA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9431', '9121', 'KABUPATEN MAMBERAMO TENGAH', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9432', '9122', 'KABUPATEN YALIMO', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9433', '9125', 'KABUPATEN PUNCAK', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9434', '9126', 'KABUPATEN DOGIYAI', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9435', '9127', 'KABUPATEN INTAN JAYA', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9436', '9128', 'KABUPATEN DEIYAI', '94', now());
insert into master_kota(kode_kota, kode_kota_capil, nama_kota, kode_provinsi, created_at) VALUES ('9471', '9171', 'KOTA JAYAPURA', '94', now());