insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (1,'BAPAK', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (2,'IBU', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (3,'KAKAK', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (4,'ADIK', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (5,'SUAMI', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (6,'ISTRI', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (7,'ANAK', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (8,'SAUDARA', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (9,'PAMAN', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (10,'TANTE', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (11,'KEPONAKAN', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (12,'KAKEK', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (13,'NENEK', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (14,'CUCU', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (15,'CICIT', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (16,'BAPAK MERTUA', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (17,'IBU MERTUA', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (18,'MENANTU', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (19,'KAKAK IPAR', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (20,'ADIK IPAR', now());
insert into option_hubungan_emergency(id, label_hubungan_emergency, created_at) VALUES (21,'TETANGGA', now());
insert into option_status_pekerjaan(id, label_status_pekerjaan, created_at) VALUES (1,'Karyawan Tetap', now());
insert into option_status_pekerjaan(id, label_status_pekerjaan, created_at) VALUES (2,'Karyawan Kontrak', now());
insert into option_status_pekerjaan(id, label_status_pekerjaan, created_at) VALUES (3,'Honorer', now());
insert into option_status_pekerjaan(id, label_status_pekerjaan, created_at) VALUES (4,'Tidak Kerja', now());
insert into option_status_pekerjaan(id, label_status_pekerjaan, created_at) VALUES (5,'Karyawan Paruh Waktu', now());
insert into option_status_pekerjaan(id, label_status_pekerjaan, created_at) VALUES (6,'Lainnya', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (1,'BELUM/TIDAK BEKERJA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (2,'MENGURUS RUMAH TANGGA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (3,'PELAJAR/MAHASISWA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (4,'PENSIUNAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (5,'PEGAWAI NEGERI SIPIL', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (6,'TENTARA NASIONAL INDONESIA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (7,'KEPOLISIAN RI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (8,'PERDAGANGAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (9,'PETANI/PEKEBUN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (10,'PETERNAK', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (11,'NELAYAN/PERIKANAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (12,'INDUSTRI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (13,'KONSTRUKSI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (14,'TRANSPORTASI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (15,'KARYAWAN SWASTA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (16,'KARYAWAN BUMN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (17,'KARYAWAN BUMD', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (18,'KARYAWAN HONORER', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (19,'BURUH HARIAN LEPAS', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (20,'BURUH TANI/PERKEBUNAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (21,'BURUH NELAYAN/PERIKANAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (22,'BURUH PETERNAKAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (23,'PEMBANTU RUMAH TANGGA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (24,'TUKANG CUKUR', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (25,'TUKANG LISTRIK', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (26,'TUKANG BATU', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (27,'TUKANG KAYU', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (28,'TUKANG SOL SEPATU', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (29,'TUKANG LAS/PANDAI BESI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (30,'TUKANG JAHIT', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (31,'TUKANG GIGI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (32,'PENATA RIAS', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (33,'PENATA BUSANA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (34,'PENATA RAMBUT', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (35,'MEKANIK', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (36,'SENIMAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (37,'TABIB', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (38,'PARAJI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (39,'PERANCANG BUSANA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (40,'PENTERJEMAH', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (41,'IMAM MESJID', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (42,'PENDETA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (43,'PASTOR', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (44,'WARTAWAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (45,'USTADZ(AH)/MUBALIGH', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (46,'JURU MASAK', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (47,'PROMOTOR ACARA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (48,'ANGGOTA DPR-RI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (49,'ANGGOTA DPD', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (50,'ANGGOTA BPK', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (51,'PRESIDEN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (52,'WAKIL PRESIDEN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (53,'ANGGOTA MAHKAMAH KONSTITUSI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (54,'ANGGOTA KABINET/KEMENTERIAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (55,'DUTA BESAR', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (56,'GUBERNUR', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (57,'WAKIL GUBERNUR', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (58,'BUPATI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (59,'WAKIL BUPATI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (60,'WALIKOTA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (61,'WAKIL WALIKOTA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (62,'ANGGOTA DPRD PROVINSI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (63,'ANGGOTA DPRD KABUPATEN/KOTA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (64,'DOSEN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (65,'GURU', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (66,'PILOT', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (67,'PENGACARA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (68,'NOTARIS', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (69,'ARSITEK', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (70,'AKUNTAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (71,'KONSULTAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (72,'DOKTER', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (73,'BIDAN', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (74,'PERAWAT', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (75,'APOTEKER', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (76,'PSIKIATER/PSIKOLOG', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (77,'PENYIAR TELEVISI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (78,'PENYIAR RADIO', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (79,'PELAUT', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (80,'PENELITI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (81,'SOPIR', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (82,'PIALANG', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (83,'PARANORMAL', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (84,'PEDAGANG', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (85,'PERANGKAT DESA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (86,'KEPALA DESA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (87,'BIARAWAN/BIARAWATI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (88,'WIRASWASTA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (90,'HAKIM', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (91,'HAKIM AGUNG', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (92,'PEGAWAI KOPERASI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (93,'TEKNISI', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (94,'PEKERJA INFORMAL', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (95,'PEKERJA SOSIAL', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (96,'PEJABAT NEGARA', now());
insert into option_pekerjaan(id, label_pekerjaan, created_at) VALUES (99,'LAINNYA', now());
insert into option_status_kepemilikan_rumah(id, label_status_kepemilikan_rumah, created_at) VALUES (1, 'Milik Pribadi', now());
insert into option_status_kepemilikan_rumah(id, label_status_kepemilikan_rumah, created_at) VALUES (2, 'Bukan Milik Pribadi', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (1, 'SD atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (2, 'SMP atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (3, 'SMA atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (4, 'D1  atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (5, 'D2  atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (6, 'D3  atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (7, 'D4  atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (8, 'S1  atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (9, 'S2  atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (10, 'S3  atau Sederajat', now());
insert into option_pendidikan(id, label_pendidikan, created_at) VALUES (11, 'Lainnya', now());
insert into option_status_pernikahan(id, label_status_pernikahan, created_at) VALUES (1, 'Belum Kawin', now());
insert into option_status_pernikahan(id, label_status_pernikahan, created_at) VALUES (2, 'Kawin', now());
insert into option_status_pernikahan(id, label_status_pernikahan, created_at) VALUES (3, 'Cerai Hidup', now());
insert into option_status_pernikahan(id, label_status_pernikahan, created_at) VALUES (4, 'Cerai Mati', now());
insert into option_agama(id,  label_agama, created_at) VALUES (1, 'Islam', now());
insert into option_agama(id,  label_agama, created_at) VALUES (2, 'Kristen', now());
insert into option_agama(id,  label_agama, created_at) VALUES (3, 'Katholik', now());
insert into option_agama(id,  label_agama, created_at) VALUES (4, 'Hindu', now());
insert into option_agama(id,  label_agama, created_at) VALUES (5, 'Budha', now());
insert into option_agama(id,  label_agama, created_at) VALUES (6, 'Khong Hu Chu', now());
insert into option_agama(id,  label_agama, created_at) VALUES (7, 'Agama Lainnya', now());